meublog/urls.py
from django.urls import path
from . import views


app_name = 'meublog'

urlpatterns = [
    path('', views.ListarPostsView.as_view(), name='listar_posts'),
    path('<slug:slug>/', views.DetalharPostView.as_view(), name='detalhar'),
    path('sharepost/<int:pk>/', views.FormContatoView.as_view(), name='share_post'),
    path('comentar/<int:pk>/', views.ComentarioView.as_view(), name='comentar_post'),
]

# <int:ano>/<int:mes>/<int:dia>

meusite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('meublog.urls', namespace='meublog'))
] 

meublog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.

class PublicadosManager(models.Manager):
    
    def get_queryset(self):
        return super(PublicadosManager, self).\
            get_queryset().filter(status='publicado')


class Post(models.Model):
    
    STATUS_CHOICES = (
        ('rascunho', 'Rascunho'),
        ('publicado', 'Publicado')
    )
    
    objects = models.Manager()
    publicados = PublicadosManager()
    
    titulo = models.CharField(max_length=255)
    slug = models.SlugField(max_length=100)
    corpo = models.TextField()
    autor = models.ForeignKey(User, on_delete=models.CASCADE, related_name='meublog_posts')
    data_publicacao = models.DateTimeField(default=timezone.now)
    data_criacao = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=9, choices=STATUS_CHOICES, default='rascunho')
    
    class Meta:
        ordering = ('-data_publicacao', )
        verbose_name = "Post"
        verbose_name_plural = "Posts"
        
    def __str__(self):
        return self.titulo


class Comentario(models.Model):
    
    post  = models.ForeignKey(Post, on_delete=models.CASCADE)
    nome = models.CharField('Nome', max_length=50)
    email = models.EmailField('E-mail')
    corpo = models.TextField('Comentario')
    data_criacao = models.DateTimeField('Data da criacao', auto_now_add=True)
    ativo = models.BooleanField('Ativo', default=False)
    
    class Meta:
        verbose_name = 'Comentario'
        verbose_name_plural = 'Comentarios'
    
    def __str__(self):
        return 'Comentario de: ' + self.nome

meublog/forms.py
from django import forms
from django.core.mail import EmailMessage

from meublog.models import Comentario



class EmailPost(forms.Form):
    nome = forms.CharField(max_length=100)
    email = forms.EmailField()
    destino = forms.EmailField()
    comentario = forms.CharField(required=False,
                                 widget=forms.Textarea)
    
    def enviar_email(self, meupost):
        nome = self.cleaned_data['nome']
        email = self.cleaned_data['email']
        destino = self.cleaned_data['destino']
        comentario = self.cleaned_data['comentario']
        
        conteudo = f'Recomendo ler o post: {meupost.titulo}\n'\
                f"Comentarios: {comentario}"
        mail = EmailMessage(
            subject=f"Recomendo esse post",
            body = conteudo,
            from_email='contato@meublog.com.br',
            to=[destino, ],
            headers={'Reply-to': email},
        )
        mail.send()


class ComentarioModelForm(forms.ModelForm):
    
    class Meta:
        model = Comentario
        fields = ['nome', 'email', 'corpo']
        
    def salvar_comentario(self, post):
        novo_comentario = self.save(commit=False)
        novo_comentario.post = post
        novo_comentario.nome = self.cleaned_data['nome']
        novo_comentario.email = self.cleaned_data['email']
        novo_comentario.corpo = self.cleaned_data['corpo']
        return novo_comentario.save()

meublog/views.py
'''from django.forms.fields import EmailField
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic.detail import DetailView 
'''
from django.contrib import messages
from django.urls import reverse_lazy 
from .forms import ComentarioModelForm, EmailPost
from .models import Post, Comentario
from django.views.generic import ListView, DetailView, FormView, CreateView
from django.shortcuts import redirect


# Create your views here.

class ListarPostsView(ListView):
    queryset = Post.publicados.all()
    context_object_name = 'posts'
    paginate_by = 2
    template_name = "meublog/post/listarposts.html"


class DetalharPostView(DetailView):
    template_name = "meublog/post/detalharpost.html"
    model = Post
    
    def _get_coments(self, id_post):
        try:
            return Comentario.objects.filter(post_id=id_post)
        except Comentario.DoesNotExist:
            raise Exception
        
    def _get_context_data(self, **kwargs):
        contexto = super(DetalharPostView, self).get_context_data(**kwargs)
        contexto['comentario'] = self._get_coments(self.object.id)
        return contexto
    
    
class FormContatoView(FormView):
    template_name = "meublog/post/sharepost.html"
    form_class = EmailPost
    sucess_url = reverse_lazy('meublog:listar_posts')
    
    def get_post(self, id_post):
        try:
            return Post.publicados.get(pk=id_post)
        except Post.DoesNotExist:
            messages.error(self.request, 'O post nao existe!')
            reverse_lazy('meublog:listar_posts')

    def get_context_data(self, **kwargs):
        contexto = super(FormContatoView, self).get_context_data(**kwargs)
        contexto['post'] = self.get_post(self.kwargs['pk'])
        return contexto
        
    def form_valid(self, form, *args, **kwargs):
        meupost = self.get_context_data()['post']
        form.enviar_email(meupost)
        messages.success(self.request,f'Post {meupost.titulo} enviado com sucesso.')
        return super(FormContatoView, self).form_valid(form, *args, **kwargs)

    def form_invalid(self, form, *args, **kwargs):
        meupost = self.get_context_data()['post']
        messages.error(self.request, f'Post {meupost.titulo} '
                                       f'não enviado.')
        return super(FormContatoView, self).form_invalid(form, *args, **kwargs)


class ComentarioView(CreateView):
    template_name = 'meublog/post/comentarios.html'
    form_class = ComentarioModelForm
    
    def _get_post(self, id_post):
        try:
            post = Post.publicados.get(pk=id_post)
            return post
        except Post.DoesNotExist:
            raise Exception
        
    def get_context_data(self, **kwargs):
        contexto = super(ComentarioView, self).get_context_data(**kwargs)
        contexto['post'] = self._get_post(self.kwargs['pk'])
        return contexto
    
    
    def form_valid(self, form, **kwargs):
        post = self._get_post(self.kwargs['pk'])
        form.salvar_comentario(post)
        return redirect('meublog:detalhar', post.slug)

meublog/templates/meublog/base.html
{% load static %}

<!DOCTYPE html>

<html lang="pt-br">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block titulo %}{% endblock %}</title>
        <meta name="description" content="meublog">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    </head>
    <body>

        <div id="content">    
            {% block conteudo %}
            {% endblock %}
        </div> <!--content-->

        <div id="sidebar">
            <h2>Meu Blog</h2>
            <p>Este é o meu Blog</p>
        </div> <!--sidebar-->

        

    <script src="{% static 'js/main.js' %}" async defer></script>
    </body>
</html>

meublog/templates/meublog/post/comentarios.html
{% extends 'meublog/base.html' %}

{% block titulo %}Meu Blog{% endblock %}



{% block conteudo %}

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Salvar">
</form>

{% endblock %}

meublog/templates/meublog/post/detalharpost.html
{% extends 'meublog/base.html' %}

{% block titulo %}Meu Blog{% endblock %}

{% block conteudo %}

    <h1>{{ post.titulo }}</h1>
    <p class="date">
        Publicado em {{ post.publicado }} por {{ post.autor }}
    </p> <!--date-->

    <p>
        {{ post.corpo|linebreaks }}
    </p>
    <br>
    <h4 style="margin-right: 0 5px;">
        <a href="{% url 'meublog:comentar_post' post.id %}">Comentar</a>
    </h4>

    {% for c in comentario %}
        <p>Comentario de {{ c.nome }}</p>
    {% endfor %}

    <h4 style="margin-right: 0 5px;">
        
    </h4>

    <!-- URL SHARE EMAIL -->
    <!-- DEIXAR OFF ATE APLICAÇÃO REAL -->
    
    <!--p style="margin-right: 0 5px;">
        <a href="{% url 'meublog:share_post' post.id %}">Compartilhar esse post</a>
    </p-->

{% endblock %}

meublog/templates/meublog/post/listarposts.html
{% extends 'meublog/base.html' %}

{% block titulo %}Meu Blog{% endblock %}

{% block conteudo %}
    <h1>Meu Blog</h1>

    <div>
        {% if messages %}
            {% for m in messages %}
                <p>{{ m }}</p>
            {% endfor %}
        {% endif %}
    </div>

    {% for p in posts %} 
        <h2>
            <!--a href="{{ p.get_absolute_url }}">{{ p.titulo }}</a-->
            <a href="{% url 'meublog:detalhar' p.slug %}">{{ p.titulo }}</a>
        </h2>

        <p class="date">Publicado em: {{ p.data_publicacao }}, por {{ p.autor }}</p><!--date-->

        <p>
            {{ p.corpo|truncatewords:15|linebreaks }}
        </p>
    {% endfor %}

    {% include "paginacao.html" with page=page_obj %}
    
{% endblock %}

meublog/templates/meublog/post/sharepost.html
{% extends "meublog/base.html" %}
{% block titulo %} Enviando o post {{ post.titulo }} {% endblock %}

{% block conteudo %}
    <h1>Enviar post: {{ post.titulo }} por email</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Enviar">
    </form>
{% endblock %}

meublog/templates/paginacao.html
<div class="pagination">

    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}"> Pagina Anterior </a>
        {% endif %}

        <span class="current">
            Pagina {{ page.number }} de {{ page.paginator.num_pages }}
        </span>

        {% if page.has_next %}

            <a href="?page={{ page.next_page_number }}">Proxima Pagina</a>

        {% endif %}

    </span> <!--step-links-->

</div> <!--pagination-->